### PR TITLE
Haskellng exprs

### PR DESCRIPTION
**Pull request by shlevy**
This creates nix expressions for use with the new haskellng infrastructure (using `cabal2nix` 2.0). `shell.nix` can be used with `nix-shell` directly, while `default.nix` needs to be passed to `haskell-ng.packages.ghcHEAD.callPackage`.

`shell.nix` requires a fairly recent nixpkgs checkout. If we're OK with going this route (including the dependency on the `7.10` prerelease), we can backport the necessary changes to the `14.12` stable branch.

The packages required to use `nix-shell` against the current nixpkgs master are currently building on `hydra.zalora.com` and should be accessible from there soon.

### CODE REVIEW

**Comment by proger** [comment]
I'm excited about 7.10 as well but what's exactly the problem with using a stable compiler?

**Comment by shlevy** [comment]
See https://github.com/NixOS/cabal2nix/commit/30d78b58545572fdad172cae0ab2c879bbea2a8c#commitcomment-9206465 . If it's important I can put some more time into fixing it, obviously it works with `cabal-install` so we should in principle be able to get it to work with nix, it's just a matter of figuring out all the problems and putting the work in.

**Comment by phunehehe** [comment]
There is quite some duplicated code between `default.nix` and `shell.nix`. Is there some existing/easy way to deduplicate them?

The fact that the installation works with `cabal-install` but not with Nix is a little disappointing, but I guess that's the price we have to pay for using new technologies. In any case, if GHC 7.10 doesn't break our code and is reasonably simple to maintain, I don't mind using it as a workaround.

Currently building this against latest Nixpkgs (merged from the tips of master of zalora/nixpkgs and nixos/nixpkgs).

**Comment by phunehehe** [comment]
I added this to a local checkout of nixpkgs (copied from default.nix) but having missing dependencies.

```
  aws-cli = callPackage
      ({ mkDerivation, amazonka, amazonka-cloudwatch, base, lens
       , optparse-applicative, resourcet, stdenv, text
       }:
       mkDerivation {
       pname = "aws-cli";
       version = "0.1.0.0";
       src = /path/to/aws-cli;
       isLibrary = false;
       isExecutable = true;
       buildDepends = [
       amazonka amazonka-cloudwatch base lens optparse-applicative
       resourcet text
       ];
       homepage = "https://github.com/zalora/aws-cli";
       license = stdenv.lib.licenses.mpl20;
       }) {};
```

Trying to install `haskell-ng.packages.ghcHEAD.aws-cli`:

```
Configuring options-1.2.1...
Setup: At least the following dependencies are missing:
base >=4.1 && <4.8
```

Trying to install `haskellngPackages.aws-cli`:

```
Configuring retry-0.5.1...
Setup: At least the following dependencies are missing:
exceptions ==0.5.*, hspec ==1.9.*
```

**Comment by shlevy** [comment]
Pushed a deduplicating commit. aws-cli builds fine against NixOS/nixpkgs@e4c9a521ef4fdf08ac8bd2db6e74c84e9f6bfd51 (with `aws-cli.cabal` patched to allow base 4.8) I will test against latest master shortly.

**Comment by shlevy** [comment]
OK, it now works with `7.8` on master! Let me know if you need this on the release branch.

**Pull request merged**
